# -------- This file is automatically generated by LSST's sconsUtils -------- #
__version__ = "82b95b1"
__repo_version__ = "82b95b1"
__fingerprint__ = "82b95b1ec93ce58846fa674b7dca8fe0e7b3b835"
__dependency_versions__ = {
    "boost": "unknown",
    "python": "unknown",
    "base": "22.0.1-2-ga9b0f51+052faf71bd",
    "pex_exceptions": "22.0.0+7589c3a021",
    "numpy": "None",
    "cpputils": "master-g6e05de7fdc+c1283a92b8",
    "fftw": "unknown",
    "eigen": "3.3.7.lsst2-1-g398bedf",
    "ndarray": "unknown",
    "pybind11": "unknown",
    "pex_config": "22.0.1-1-g87000a6+9855668607",
    "utils": "22.0.1-7-ge754672+7bff505259",
    "daf_base": "22.0.1-5-g15c806e+279be02bb3",
    "log4cxx": "unknown",
    "log": "22.0.1-7-gba73697+279be02bb3",
    "daf_persistence": "22.0.1-4-g243d05b+4f1e4d80e3",
    "boost_math": "unknown",
    "sphgeom": "22.0.1-2-gac51dbf+052faf71bd",
    "geom": "22.0.1-5-g096abc9+bb036ca770",
    "minuit2": "unknown",
    "gsl": "unknown",
    "cfitsio": "unknown",
    "starlink_ast": "unknown",
    "astshim": "22.0.0+052faf71bd",
    "afw": "22.0.1-33-g415537ac7+f49c5b7a45",
    "meas_base": "22.0.1-19-g93a5c75+d877916f14",
}
__all__ = (
    "__version__",
    "__repo_version__",
    "__fingerprint__",
    "__dependency_versions__",
)
